### ISSUE TITLE
transcript sequence assembly in codon_usage.R

### ISSUE THREAD

**Issue by Joon-20** [LabTranslationalArchitectomics/riboWaltz#10]
Hi, Thanks for the wonderful tool. I have been testing different ribo-seq packages and I am quite excited about riboWaltz.

I was struggling with codon_usage_psite (or codon_usage.R), with my genome Fasta file and GTF file to generate "sequences" (DNAStringSet). I think there is an error regarding the assembly of transcript sequence from individual exons. It worked fine for those in the + strand but not for the - strand. 

Is there a way you can fix this error?
Thank you very much,
Joon

Part of the code is :   
        seq_df <- sub_exon[, list(seq = paste(Biostrings::subseq(temp_sequences[as.character(seqnames)],
                                                                 start = start,
                                                                 end = end), collapse="")),
                            by = group_name]

**Comment by fabiolauria** [comment]
Hi,
thanks for using riboWaltz.
this is to inform you I'm working on the issue. I have already found out what is likely to be the problem. I'll send you a function to be tested with your data as soon as I solve it.

Bests,
Fabio

**Comment by Joon-20** [comment]
Dear Fabio,
Thanks for the update. Yes, it will be a great help! Again, thanks for the awesome tool!
Best,
Joon

**Comment by fabiolauria** [comment]
Hi Joon,
below you find a .zip archive including an .R file with a new version of _codon_usage_psite_ function, called **_codon_usage_psite_test_**. Please run the new function using your data and let me know if it works. It should be ok, since I just run it on mouse genome FASTA and GTF from GENCODE and I got the correct nucleotide sequences also for transcripts on the reverse strand.
If it doesn't work, I'll ask you some details about your data to try and understand where the problem is. In fact, some misunderstandings have arisen about the sort of alignments riboWaltz can handle but I am still working on the documentation to make everything clear.

[codon_usage_test.zip](https://github.com/LabTranslationalArchitectomics/riboWaltz/files/2519794/codon_usage_test.zip)

**Comment by Joon-20** [comment]
Hi Fabio,

Thank you very much. The fix worked perfectly well! 
Relieved and excited to see the stop codons are now gone from the codon_usage_plot!
I will close the issue. Thanks again, Joon

**Comment by fabiolauria** [comment]
Hi Joon,
I'm very happy to hear everything is ok. I'll substitute the old function with the new one in a while.
Thank you again for the tip.

Bests,
Fabio
