### ISSUE TITLE
bedtolist: error in setnames(x, value): can't assign 5 names to 6 column data.table

### ISSUE THREAD

**Issue by morganeboone** [LabTranslationalArchitectomics/riboWaltz#11]
Hi, 

I've been unsuccessful in using riboWaltz on my large dataset (6x 300M reads) so far. I used STAR to map my paired-end reads to the mouse GRCh38.92 genome from Ensembl with accompanying GTF file, which I also used with _create_annotation_ to generate the annotation table. Transcript IDs should thus match in both.

When I use the bamtolist function, I get
"Error in bamtolist(bamfolder = bams,  : 
  %s M  (%s %%) reads removed: referece transcript ID not found in the annotation table"

When I instead generate a bed file from my bam file, and use the bedtolist function, I get
"Error in setnames(x, value): can't assign 5 names to 6 column data.table" 

What am I overseeing?

**Comment by fabiolauria** [comment]
Hi,
thank you for using riboWaltz and for reporting the issue.
First of all, thank for pointing out the bug related to the message "%s M (%s %%) reads removed: reference transcript ID not found in the annotation table". Obviously, it should have report the number and percentage of reads actually removed.
In particular, this error pops up when there is a 100% discrepancy between transcript IDs in the BAM and in the annotation file. This is odd, since you used a genome and a GTF file from the same source.
Are you sure the version of the transcripts is reported (or not reported) in their ID in both files? Sometimes in BAM files it is there even if the alignment was performed using a GTF file that doesn't include transcript version (see parameter rm_version).
Are you using BAM files based on _transcript coordinates_ (i.e. BAM generated by the --quantMode TranscriptomeSAM option of STAR)? If so, remember that you must specify the original alignment was actually performed on the whole genome and translated in transcript coordinates later (see parameter transcript_align).

If you are doing everything properly, please feel free to send my a chunk of your BAM file and the annotation data.table even by e-mail. So I can try and find out the problem.

Bests,
Fabio

**Comment by morganeboone** [comment]
Hi Fabio,
you were right, after taking a closer look it turns out that it is only by specifying --quantMode in STAR the transcript coordinates are reported in the bam, and there is no direct way to use the genome bam in riboWaltz. I somehow thought that the annotation table created with create_annotation from the GTF file would include genomic coordinates as well.
Thank you for clearing that up, it runs smoothly now!

Best,
Morgane
