### ISSUE TITLE
Errors when providing fastapath with psite_info and codon_usage_psite

### ISSUE THREAD

**Issue by morganeboone** [LabTranslationalArchitectomics/riboWaltz#13]
Hello Fabio,

most riboWaltz functions run smoothly on my current dataset (genome alignment of RFPs with STAR --quantMode reporting transcript coordinates, annotation created with the create_annotation function on the corresponding GTF file). However, I cannot seem to get beyond certain errors with functions that require to specify the fastapath and GTF file. 

For example, to extract the 3 nucleotides of the P-site, A-site, and E-site: 
`reads_allsites_list <- psite_info(reads_list, psite_offset, site=c("psite","asite","esite"), fastapath="genome.fa", gtfpath="genome.gtf")`
I get
Error: cannot subset by character when names are NULL
while the function itself (when not specifying site, fastapath, or gtfpath) seems to work fine.

Same for generating a codon usage bar graph with codon_usage_psite:
`cu <- codon_usage_psite(reads_psite_list, annotation, sample="sample1A", fastapath="genome.fa", gtfpath="genome.gtf")` 
I get
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in eval(expr, envir, enclos) : could not find function "width"

Although the errors are different I wonder if both are related because they both require specifying a fasta+GTF file. The fasta file is the same genomic assembly that I used for the mapping however, I don't see how there could be anything wrong with it. 

Thanks
Morgane

**Comment by fabiolauria** [comment]
Hi Morgane,

Hmmm...I cannot understand why, if the problem is the GTF file, you get different errors from the two functions. They use the very same chunk of code for reading and handling the file. However, I checked both functions again and at least for _codon_usage_psite_ it seems it couldn't find the function _width_ from Biostrings.
Below you find a .zip archive including an .R file with a slightly different version of _codon_usage_psite_ function, called **codon_usage_psite_test**. Please run the new function using your data and let me know if it works. I just run it on mouse genome FASTA and GTF from GENCODE and I got all sequences without errors. Meanwhile I'll look deeper into _psite_info_.

Bests
Fabio

[codon_usage_test.zip](https://github.com/LabTranslationalArchitectomics/riboWaltz/files/2623616/codon_usage_test.zip)

**Comment by morganeboone** [comment]
Hi Fabio,

great, the **codon_usage_psite_test** function works, at least to generate codon usage bar graphs. It does not return a scatter plot when specifying a custom codon usage table (with columns "codon" and "values") with the codon_values option, however:
`cu <- codon_usage_psite_test(reads_psite_list, annotation, sample="sample1A", fastapath="genome.fa", gtfpath="genome.gtf", codon_values= custom_cu)`

There are no error notices but I still get a bar graph instead of the scatter plot.

Best
Morgane

**Comment by morganeboone** [comment]
Hi Fabio,

you're right, I erronously just plotted with cu[["plot"]] iso cu[["plot_comparison"]]. Thanks!

Morgane
