### ISSUE TITLE
codon_usage_psite error

### ISSUE THREAD

**Issue by charlin90** [LabTranslationalArchitectomics/riboWaltz#16]
Hi，I am using riboWaltz package, it is a wonderful tool for ribo-seq data analyses. Unfortunately, I meet an error while using codon_usage_psite function, the error message as follows:

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error: subscript contains invalid names
In addition: Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.

I also try codon_usage_psite_test function, but the same error messages were given. I really don't know how to solve it, can you help me? I will be very appreciate for your any help.

Best Wishes
Charlin

**Comment by charlin90** [comment]
Hi Fabio,

Thanks for your reply! I got the function usage_psite_test from Issue #13，as you referred. I also used the function usage_psite in the package. Both they gave the same error messages. 

For the FASTA file I used, the header is simple, and it only contains transcript name, as follows:

![image](https://user-images.githubusercontent.com/11549300/52114730-c455c680-2647-11e9-8347-dbe4f4fe3d1c.png)

In addition, the data.tables I used is as follows:
![image](https://user-images.githubusercontent.com/11549300/52115194-fb78a780-2648-11e9-80b4-c9797f0531e7.png)

gtf file was download from Ensembel website.

So, the gene names in  FASTA files and input data.tables are consistent. Maybe there are some other problems?

Best Wishes
Charlin

**Comment by fabiolauria** [comment]
Hi Charlin.
You are right, transcript names are consistent.
Since you aligned on transcript sequences, however, I think you set fasta_genome = TRUE. It is likely the reason why riboWaltz starts to process GTF files and create TxDb objects returning messages like

Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK

As reported in its [manual](https://github.com/LabTranslationalArchitectomics/riboWaltz/blob/master/ReferenceManual.pdf), for transcriptome alignments riboWaltz find all the information required for sequences analyses in the annotation data.table and FASTA file, no need to specify a GTF.

Hope this helps.
Bests,
Fabio

**Comment by charlin90** [comment]
Hi Fabio,
You are right. I have recognized the problem you said after I firstly posted the question and revised it as you said. Unfortunately, I still encountered the same error message:

Error: subscript contains invalid names.

![image](https://user-images.githubusercontent.com/11549300/52120695-19013d80-2658-11e9-9753-331b091b4cac.png)

Best Wishes
Charlin

**Comment by fabiolauria** [comment]
Hi Charlin.
Ummm I am pretty sure this a problem related to transcript names even if I can't figure it out. Even worse if it has nothing to do with names. So, step by step, could you please run the following lines and write me back with the final output?

name_tr <- unique(reads_psite_list[[**SAMPLE_NAME**]]$transcript)
sequences <- Biostrings::readDNAStringSet(**YOUR_FASTA**, format = "fasta", use.names = TRUE)
name_seq <- names(sequences)
table(name_tr %in% name_seq)

Thank you.
Bests
Fabio

**Comment by fabiolauria** [comment]
Ok, so it's not about names.
It's very strange, I've just checked the function and it worked properly with different options, at least with my own datasets. One last thing before asking you chunks of your datasetes: could you please run again function _psite_info_ specifying the following options?

site = "psite"
fastapath = **YOUR_FASTA**
fasta_genome = FALSE

They are used to add a column reporting sequences of triplets covered by the p-site, similarly to what should be done by codon_usage_psite. This way we will be able to understand if the problem is related to this initial step of the process rather then to the plot itself.

Bests,
Fabio

**Comment by charlin90** [comment]
Hi Fabio,
I know where the error is. I carefully read the source code for function codon_usage_psite, and found there is an error while running command "**sub_sequences <- sequences[c_transcript]**", the error message is as above mentioned:
![image](https://user-images.githubusercontent.com/11549300/52126065-3f7ba480-2669-11e9-8133-59ed25621309.png)

![image](https://user-images.githubusercontent.com/11549300/52126114-56ba9200-2669-11e9-8628-223c429c107c.png)

Indeed, when I set frequency_normalization as FALSE, the function codon_usage_psite successfully works.Thus, it seems that the code for **frequency_normalization** may need some revisions.

Best Wishes
Charlin

**Comment by charlin90** [comment]
Hi Fabio,

For my question, I seem to understand. I made my FASTA file from gtf file, while I only considered the transcripts from human chromsomes 1-22,X,Y and MT, other transcripts from weird chromsomes were discard. This caused that the transcripts in FASTA file is a subset of GTF file. Thus when parameter transcripts( function codon_usage_psite) is set as NULL，some transcripts in GTF file can not be found in FASTA file, resulting in the error----"subscript contains invalid names".

Many thanks for your great help!

Best Wishes
Charlin

**Comment by fabiolauria** [comment]
Hi Charlin.
Sorry for the delay. I have read your second to last comments but then I got busy and didn't menage to answer you. I was about to write you again that the problem was likely due to mismatches of transcript names but I can see you already solved it. Great!
I think I'll add some kind of warning or error message to prevent similar issues.

Bests,
Fabio
