### ISSUE TITLE
read length calculation question

### ISSUE THREAD

**Issue by charlin90** [LabTranslationalArchitectomics/riboWaltz#17]
Hi, I am using riboWaltz package, it is really a wonderful tool.However, I have a question for the calculation of distribution of read length. In my case, the read lengths were range from 25 to 34, but _rlength_distr_ method gave abnormal distribution of read lengths(21-150). I checked the source code of combine_bam.R script, and found the author considered the width of GAlignments object  as the read length,instead of qwidth. In fact, qwidth is true read length.
![image](https://user-images.githubusercontent.com/11549300/52625214-749ab900-2eeb-11e9-9233-6206453a89cc.png)

Bests,
Charlin

**Comment by fabiolauria** [comment]
Hi Charlin,
thank you for the warning.
I thought quite a lot to which "width" consider. These are some of the considerations I made:
1) many features of riboWaltz require the rightmost and leftmost coordinates of mapping reads relative to the beginning of the reference sequence. For consistency's sake, the length I consider is then the one associated to the interval between the start and end of the query covered by the alignment (i.e. "width").
2) in all samples I have analysed so far, columns qwidth and width almost coincide (same values >99%): default options of the most common aligners (TopHat, STAR) force them to discard reads with very small numbers of insertions/deletions/mismatches. This results in few of "I","D" and "M" in CIGAR strings i.e. in small differences between qwidth and width (usually between -5 and 5);
3) riboWaltz currently works for alignments based on transcriptome coordinates. This means that, in principle, no long gaps in queries "covered" by mapping reads should be present (e.g. from alignments on splicing junctions). How come in your sample reads of 34 nts (max) align on regions of 150 nts?

What I can do is to include a filter to discard all reads with qwidth-width > n where _n_ is an integer number specified by the user. As I said, Less than 1% of the reads would be discarded (would it be true also for your sample?).

Let me know what you think. Suggestions are welcome.

Bests
Fabio

**Comment by charlin90** [comment]
Hi Fabio,thanks for your reply. 
To the best of my knowledge, "width" represent matched size of a read,instead of true read length. In my work, we revised "width" as "qwidth" in combine_bam.R script, and I got the expected results(25-34nt). Despite columns "qwidth" and "width" may be almost same, but there is still a small difference between them. This may be avoided through using "qwidth", and qwidth may be more reasonable. For 150 nts I said before, I did not conduct more detailed check, because I found that "width" represent matched size of a read instead of true read length at the time. Thus, I revised it based on your code, and got my expected results.

Thanks for your good work. 
Sincerely,
Charlin

**Comment by charlin90** [comment]
Hi Fabio,
I have already performed the command you gave, the results are as follows,
![image](https://user-images.githubusercontent.com/11549300/52845173-634aea00-3141-11e9-8e9f-6c3afad365a9.png)

I also give what width 150 is, and width is the sum of non S characters(in cigar). I have already revised width as qwidth, and the program works well.

Yours,
Charlin

**Comment by fabiolauria** [comment]
Hi Charline,
thank you for your superfast response.

You persuaded me to switch from one width to the other since riboWaltz seems to work (better). Also because my previous idea to include a filter to discard all reads showing qwidth-width > n is not suitable for dataset as yours. In fact, the percentage of reads with different _width_ and _qwidth_ is very high and to throw everything away would mean to waste lot of material.

One last comment: you can for sure use width to get correct read length distribution. Still, I think it would be worth to investigate the wide discrepancy between read length and length of covered regions. I can see from your results that the difference of 120nts is due to the 120 Ns (in CIGAR). In [this document](http://samtools.github.io/hts-specs/SAMv1.pdf) N character is described as "skipped region from the reference" and "for mRNA-to-genome alignment, an N operation represents an intron. For other types of alignments, the interpretation of N is not defined". Even if you aligned on genome, data displayed above are in transcriptome coordinates, so no Ns should be there (or at least would be odd).

I still need to verify few things then I'll proceed to modify the code. Meanwhile I'll close this issue. 
Thanks again for your tip.

Bests,
Fabio
