### ISSUE TITLE
riboWaltz works in interactive mode but not in scripted mode within pipeline

### ISSUE THREAD

**Issue by j-berg** [LabTranslationalArchitectomics/riboWaltz#22]
RiboWaltz just gives warning when run in interactive mode and the output psite table seems to be fine, but if using the same exact commands within the XPRESSpipe Rscript, it triggers an error instead of a warning. A possible issue might be that I am testing using a small example dataset, but I am at a loss as to how to fix this. Any help would be appreciated!

### Command:
```
p_sites <- psite(reads_list)
```

### Interactive output:
```
processing SRR2075925_ribo_DMSO_rep1_smal_Aligned.toTranscriptome.out
best offset: 18 nts from the 3' end
 best offset: 19 nts from the 3' end
Warning messages:
1: In if (extremity == "auto" & ((best_from3_tab[, perc] > best_from5_tab[,  :
  the condition has length > 1 and only the first element will be used
2: In `[.data.table`(offset_temp, is.na(corrected_offset_from_3), `:=`(corrected_offset_from_3,  :
  Supplied 2 items to be assigned to 15 items of column 'corrected_offset_from_3' (recycled leaving remainder of 1 items).
```

### Rscript output:
```
processing SRR2075925_ribo_DMSO_rep1_smal_Aligned.toTranscriptome.out
best offset: 18 nts from the 3' end
 best offset: 19 nts from the 3' end
Error in `[.data.table`(offset_temp, is.na(corrected_offset_from_3), `:=`(corrected_offset_from_3,  : 
  Supplied 2 items to be assigned to 15 items of column 'corrected_offset_from_3'. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.
Calls: psite -> [ -> [.data.table
In addition: Warning message:
In if (extremity == "auto" & ((best_from3_tab[, perc] > best_from5_tab[,  :
  the condition has length > 1 and only the first element will be used
Execution halted
```

**Comment by j-berg** [comment]
Adding to the mystery...

When I run `p_site <- psite(reads_list)` in the R Console, then look at the reads_list object again, there is no chance, but when I run the command in the scripted mode, the psite function fails and when I go back to look at the reads_list object it has been modified.

Interactive/R Console
```
> reads_list
$SRR2075925_ribo_DMSO_rep1_smal_Aligned.toTranscriptome.out
           transcript end5 end3 length cds_start cds_stop
   1: ENST00000600289  491  508     18        41      250
   2: ENST00000252816  355  372     18        52      429
   3: ENST00000593829  600  617     18       255      674
   4: ENST00000481016  193  219     27         0        0
   5: ENST00000596811  658  685     28         0        0
  ---                                                    
1629: ENST00000597224  544  569     26         1      732
1630: ENST00000594443  534  559     26        71      193
1631: ENST00000593503  314  339     26         0        0
1632: ENST00000221801  809  834     26        80     1045
1633: ENST00000595545  475  500     26         1      690
```

Scripted 
```
> p_sites <- psite(reads_list)
processing SRR2075925_ribo_DMSO_rep1_smal_Aligned.toTranscriptome.out
best offset: 18 nts from the 3' end
 best offset: 19 nts from the 3' end
Error in `[.data.table`(offset_temp, is.na(corrected_offset_from_3), `:=`(corrected_offset_from_3,  : 
  Supplied 2 items to be assigned to 15 items of column 'corrected_offset_from_3'. The RHS length must either be 1 (single values are ok) or match the LHS length exactly. If you wish to 'recycle' the RHS please use rep() explicitly to make this intent clear to readers of your code.
In addition: Warning message:
In if (extremity == "auto" & ((best_from3_tab[, perc] > best_from5_tab[,  :
  the condition has length > 1 and only the first element will be used
> p_sites
Error: object 'p_sites' not found
> reads_list
$SRR2075925_ribo_DMSO_rep1_smal_Aligned.toTranscriptome.out
           transcript end5 end3 length cds_start cds_stop site_dist_end5
   1: ENST00000600289  491  508     18        41      250            450
   2: ENST00000252816  355  372     18        52      429            303
   3: ENST00000593829  600  617     18       255      674            345
   4: ENST00000481016  193  219     27         0        0            193
   5: ENST00000596811  658  685     28         0        0            658
  ---                                                                   
1629: ENST00000597224  544  569     26         1      732            543
1630: ENST00000594443  534  559     26        71      193            463
1631: ENST00000593503  314  339     26         0        0            314
1632: ENST00000221801  809  834     26        80     1045            729
1633: ENST00000595545  475  500     26         1      690            474
      site_dist_end3
   1:            467
   2:            320
   3:            362
   4:            219
   5:            685
  ---               
1629:            568
1630:            488
1631:            339
1632:            754
1633:            499
```

**Comment by fabiolauria** [comment]
Hi.
First of all, I must say I am not familiar with scripted mode and XPRESSpipe Rscript, so I don't really know what you are talking about, sorry. I googled XPRESSpipe and I found your github page. Still, it's not clear to me if riboWaltz is somehow included in the pipeline. If not, I cannot understand what do you mean by "using the same exact commands within the XPRESSpipe Rscript". Is it a way of running R scripts using Python? Could you please clarify this point to me?

Given this, I'm pretty sure the warning you reported in your first post is caused by the presence of two identical global maximum. This is not a common scenario and, as you suggested, can be due to the small example dataset. What I can do for getting rid of this specific issue is to instruct riboWaltz to choose one of the two or more global maximum and discard the other(s). I'll do it. However, it seems that the error returned by the scripted mode is somehow a wrong interpretation of R warnings by Python (?), not related to riboWaltz or R. 

Regarding your second post, the fact that _reads_list_ is updated in scripted mode is expected. The whole code is based on data tables i.e. data structures are automatically updated and replaced even without assigning any new data table to them. The additional columns _site_dist_end5_ and _site_dist_end3_ are generated to compute the p-site offset and then removed at the end of the process. Since the scripted mode throws an error before their removal, you can still see the two columns when looking at _reads_list_.

Hope everything is clear.

Bests,
Fabio

**Comment by j-berg** [comment]
Hi Fabio,

Thanks for the response and clarification. I've been running larger files with no issue.

The variable behavior was occurring between an R interpreter in command line or by running an Rscript from the command line and running it manually in Rstudio or something similar. Everything I was doing to produce those different outcomes was entirely in R, which is why I was so confused as to how the two were resulting in differences.
