### ISSUE TITLE
Error in (function (x)  : attempt to apply non-function in acquiring input files step

### ISSUE THREAD

**Issue by kdc1127** [LabTranslationalArchitectomics/riboWaltz#29]
Hello! Thanks for this R package.  Our lab is trying riboWaltz on Neurospora ribo-seq data. I think I've managed to load the annotation file, and when I try the code:
reads_list <- bamtolist(bamfolder = "/KDC/ribowaltz_test", annotation = annotation_ncrassa)

It gives me this error,
Error in (function (x)  : attempt to apply non-function

But also gives this out as an output:
#Input reads: 38.510 M
#Good! Number of indel below indel_threshold for all reads. No reads removed.
#Great! All reads' reference transcript IDs were found in the annotation table. No reads removed.
#0.199 M  (0.517 %) reads removed: mapping on negative strand.
#Output reads: 38.311 M
#Done! wt1_28_Aligned.toTranscriptome.out.bam has been loaded as wt1_28_Aligned.toTranscriptome.out .

It looks like it ran, but I am just wondering what that error is all about and the consequence on the outputs. If there is any other information you need, please let me know. Thanks!

Kat

**Comment by fabiolauria** [comment]
Hi Kat,
thank you for filing this issue.
I have just tested the function on a couple of bam files and everything worked just fine (according to its last version I recently uploaded on github). Moreover, it's not clear in my mind how you got both an error AND the expected output from the properly working function.
Here some questions for you:
- does reads_list exist after running _bamtolist_ and getting the error? Is it empty?
- how many files are included in /KDC/ribowaltz_test?
- Is "wt1_28_Aligned.toTranscriptome.out.bam" the first file (i.e.: does riboWaltz manage to read and acquire only the first file and then stops throwing the error you reported?)
- do you still get the error by running _bamtolist_ on a single bam file?

While waiting for your response I'll check the code once more. It seems that error might be associated to bad syntax.

Bests,
Fabio

**Comment by fabiolauria** [comment]
Hi Kat.
Brief update: I rerun the function on samples mapped on the trascriptome (as yours, judging by your code) and on the genomes, with different parameters (e.g. specifying _name_samples_). Under no circumstances I got the error you reported. So I checked and tested the code line by line, with the same result.
I guess that error has something to do with your data/data structures and how they are handled by riboWaltz but I cannot be sure.

Bests
Fabio

**Comment by kdc1127** [comment]
Hi Fabio,

Thanks for the prompt response! To answer your questions:

Yes, the reads_list exist and it has data specifying our transcript IDs and other info.
I only have one test file in the folder initially. When I tested two bam files, the error appeared only on the first run, ad as you suggested stopped giving the error with the second file.

Interestingly, when a colleague tried it on her dataset, she got a different error which said, "Error in x$.self$finalize() : attempt to apply non-function" but she also generated the reads_list fine.

We've been able to do up to the p-site offset determination with the reads_list outputs. You are probably right - that the errors could be due to our data structure. I just think this is the case because my colleague and I got different errors, and these datasets came from different sequencing platforms. If you have any other ideas based on the recent error report, or some kind of check to know that we're getting the right outputs, we would appreciate it.  

Best,
Kat

**Comment by fabiolauria** [comment]
Hi Kat,
I looked for the nature of the second error message you reported ("Error in x$.self$finalize() : attempt to apply non-function"). It 
seems not related to specific packages or functions. It is likely due to "garbage collection (removal from memory of objects that are no longer in use) and this makes it tricky to pinpoint what causes it and why it does not always happen at the same spot" as discussed [here](https://stackoverflow.com/questions/61598340/why-does-rastertopoints-generate-an-error-on-first-call-but-not-second), [here](https://github.com/sneumann/xcms/issues/288) and [here](https://discourse.mc-stan.org/t/very-mysterious-debug-error-when-running-rstanarm-rstan-chains-error-in-x-self-finalize-attempt-to-apply-non-function/4746/3). I'm thinking it may depend on the R version, but I didn't find any reference about this (FYI I'm currently using v 3.6.3)
Anyway, all discussions highlight the fact that it is actually an error **message** rather than a real error. In fact, all scripts run as expected till the end, unless a for loop is involved. In this case, sometimes the error forces the loop to stop after the first cycle.
Unfortunately _bamtolist_ encloses a for loop that intervenes when multiple samples are passed. I think a potential way to bypass the issue of improper stopping is to run _bamtolist_ **within** a for loop such that it reads one file at a time and, even returning multiple errors (one for each sample), it might work.

Bests
Fabio

**Comment by kdc1127** [comment]
Hi Fabio,

You are probably right - that it has something to do with our system rather than the package. We've actually ran the other  commands past the error, and so far it's spewing the expected plots and data tables. Thanks for addressing this and suggested solutions.

Best,
Kat
