### ISSUE TITLE
Documentation of dependencies (GenomicFeatures, ggplot, cowplot)

### ISSUE THREAD

**Issue by bontus** [LabTranslationalArchitectomics/riboWaltz#3]
Hi,
I noticed that your package currently does not load dependencies automatically and that they are also not mentioned in the vignette. So far, I found GenomicFeatures for importing BAM/GTF files, ggplot/cowplot for creating plots during psite() calculations as well as Biostrings for codon sequence analysis in psite_info() to be missing, so they need to be loaded manually.
Best

**Comment by fabiolauria** [comment]
Hi,
thank you for your comments. I updated the documentation (both the vignette and the readme) adding a paragraph reporting the dependencies.
I'm not sure why they are not automatically loaded since all the dependencies are listed both in the DESCRIPTION file and in NAMESPACE. I'll try to fix this problem problem as soon as possible.

Bests,
Fabio
