### ISSUE TITLE
Dealing with multiple input bam files

### ISSUE THREAD

**Issue by kdc1127** [LabTranslationalArchitectomics/riboWaltz#36]
Hi! This may be a very basic R question, but I am wondering how can I extract the psite_info table for each bamfile input if I ran the code for multiple bamfiles. If I have a single bamfile, this code works fine:

>reads_psite_list <- psite_info(reads_list, psite_offset)

Output
processing rp_sample1_Aligned.toTranscriptome.out
1. adding p-site position
2. adding transcript region

>write.table(reads_psite_list,"rp_sample1_psites.txt")

When I run the code for say two bamfiles, I believe this runs just fine:

> reads_psite_list <- psite_info(reads_list, psite_offset)

Output
processing rp_sample1_Aligned.toTranscriptome.out
1. adding p-site position
2. adding transcript region
processing rp_sample2_Aligned.toTranscriptome.out
1. adding p-site position
2. adding transcript region

But how can I extract a psite info table for each sample? Also, is there a limit to the number of bam files it can analyze simultaneously? Thanks so much for the help.

Best,
Kat

**Comment by fabiolauria** [comment]
Hi Kat,
thank you for using riboWaltz.

Generally speaking, riboWaltz works with **lists** of data.tables, whether you analyze single samples (i.e. BAM files) or multiple samples. Thus, the output of _bamtolist_, _psite_info_ and the input of most functions are **lists** of data.tables. Only exceptions are the functions _create_annotation_ and _psite_ that returns data.tables. 
This means that if you want to extract and write the output of _psite_info_ run on multiple samples, you have to select the elements of interest and write them separately. The name of the elements of reads_psite_list can be obtained by 

`names(reads_psite_list)`

and you can extract and write them by 

```
write.table(reads_psite_list[["name_first_element"]], "rp_sample1_psites.txt")
write.table(reads_psite_list[["name_second_element"]], "rp_sample2_psites.txt")
...
```

or by 

```
write.table(reads_psite_list[[1]], "rp_sample1_psites.txt")
write.table(reads_psite_list[[2]], "rp_sample2_psites.txt")
...
```

I guess you could use a for loop or other clever and faster scripts as well.
Just to be clear, unless you have specific reasons to write the psite_info tables on txt files (e.g. store it for external usage), I would suggest to save reads_psite_list as an RData and load it whenever you need it. This way, you wouldn't need to save the info related to each sample in a different txt file and you would also save a lot of space on the disk.


Finally, in principle there is no limit to the number of BAM files riboWaltz can analyze simultaneously. However, the performance of your machine is highly connected with the maximum number of files that can be acquired and the processed at once.


Let me know if everything is clear or if you need additional explanations.

Best
Fabio

**Comment by kdc1127** [comment]
Hi Fabio,

Thanks for the reply, and yes, riboWaltz has been useful for us. Yes, they were big files and I agree with your suggestion. I hope it's okay if I describe here what we are trying to achieve, and maybe seek for your advice whether RiboWaltz can address it. We are trying to look for stop codon readthrough (3'utr reads), and look at differences between WT and a mutant involved in translational fidelity. It is however made more complex, because we wanted to see if there are "rhythms" in readthrough. That means we hope to see oscillating levels of reads on the 3'utr for WT time course samples, which should be lost in the mutant. However, we believe we need to identify first that the reads in the 3'utr are centered in the ribosome, and not just spurious/background reads. My initial thought is to isolate all genes with p-site offset info in the 3'utr across all time points for wt and mutant (there's not a lot as expected). Getting the text files I guess will allow me to grep/isolate only the info for the 3'utr. Moreover, we would also want to generate the periodicity plots relative to the stop codon similar to https://elifesciences.org/articles/52611/figures#content. I appreciate any thoughts that you may have, or if this approach makes sense with regards to answering our question. 

As far as the analysis goes, I was able to generate most of the plots specified in your documentation, and now working on the codon coverage analysis. It's a struggle for somebody who doesn't have much R training, but I'm learning a lot. It's been a great resource so far!

Best,
Kat

**Comment by fabiolauria** [comment]
Hi Kat.
I know R may be difficult for beginners, but I think that whatever is needed for the analysis you described can be achieved using it. Whether exploiting riboWaltz or not.

> However, we believe we need to identify first that the reads in the 3'utr are centered in the ribosome, and not just spurious/background reads.

I completely agree on this: you should check for the periodicity associated to those ribosomes falling on the 3'UTR, or at least at the beginning of the 3'UTR. Otherwise, no considerations about potential translating ribosomes could be done.

> My initial thought is to isolate all genes with p-site offset info in the 3'utr across all time points for wt and mutant (there's not a lot as expected). Getting the text files I guess will allow me to grep/isolate only the info for the 3'utr. 

This is a good idea. For each sample, you can easily subset the corresponding data.table in R using the column _psite_region_, which reports the localization of the P-site along the three region of the transcripts. Problem is that for the transcripts that are not supposed to be protein coding (those reporting "0" in columns _start_pos_ and _stop_pos_), the _psite_region_ is always set to "3utr". riboWaltz knows how to deal with this but up to know for manual selections you would have to somehow keep only the protein codings to avoid biases in downstream analyses.

> Moreover, we would also want to generate the periodicity plots relative to the stop codon similar to https://elifesciences.org/articles/52611/figures#content. I appreciate any thoughts that you may have, or if this approach makes sense with regards to answering our question.

You should be able, using the function **metaprofile_psite**, to obtain the information you need for this plot. Obviously, due to the low amount of reads on the 3' UTR, they will be masked in the default plot by those mapped on the CDS. However, you can run **metaprofile_psite**, look at the data.table that is returned together with the plot and extract only the data related to the 3' UTR (i.e. the lines where the distance from the stop codon is >= 0). Starting from this data, you should be able to plot the metaprofile only for that region (with your own functions, not riboWaltz).
The good thing of this procedure is that you only have to handle the plot, while the computations are performed by riboWaltz, so in priniciple you don't need to isolate all transcripts with p-sites in the 3'UTR as discussed above. Is also possible that, if you cannot se the expected periodicity on the 3'UTR, this is because only a subset of transcript displays the readtrhough, so you would have to dig a bit in the data to identify them.
Remember that **metaprofile_psite** includes the parameter _utr3l_. You can set it in order to keep "enough nucleotides" on the 3'UTR for you analysis, even if doing so will probably reduce the number of transcripts accordingly (only transcripts with an annotated 3'UTR longer than _utr3l_ are kept).

> As far as the analysis goes, I was able to generate most of the plots specified in your documentation, and now working on the codon coverage analysis. 

I'm not sure the codon coverage analysis is something useful for your interests. Might be a good idea, after revealing genuine readthrough, to look at the codons "more involved" in this event. Again, not using riboWaltz for specific analysis.

> It's a struggle for somebody who doesn't have much R training, but I'm learning a lot.

I know. I hope the documentation accompanying the package helps.

Best
Fabio

**Comment by kdc1127** [comment]
Thank you very much for all the advice suggestions. For now, I will work on trying them.

Best,
Kat
