### ISSUE TITLE
How riboWaltz decided the CDS start and CDS end position?

### ISSUE THREAD

**Issue by Xuan0318** [LabTranslationalArchitectomics/riboWaltz#38]
Hi Fabio,

Thank you for your good software. Now I face a problem about how riboWaltz decided the CDS start and CDS end position. 

I did another m6a analysis with the ribosome position output of riboWaltz. I need to make sure I use the same way in riboWaltz to decide the CDS start and CDS end in my m6a analysis since the transcript usually has multiple start and end in Ensembl Biomart. Could you please tell me the marital or method used in riboWaltz about it?

Thank you in advance and have a nice day!

**Comment by Xuan0318** [comment]
Then I use gencode gtf file as input in riboWaltz. For ENST00000011700.10 as an example. I extract all CDS fragments with the keywords “CDS” feature and "ENST00000011700.10" from gtf file to get the CDS location and length. Then I extract all exon fragments with the "exon" feature and "ENST00000011700.10" to get the transcript location and length. After that, I could get the CDS start location on the transcript. But I found it is different between my result and the output in riboWaltz. The riboWaltz shows that CDS is from 1 to 9632 in the transcript, but my result shows that CDS is from 1 to 9629 in the transcript.

**Comment by fabiolauria** [comment]
Hi there.
riboWaltz extracts the start and the end of the CDS according to the GTF file passed as input.
To be consistent with other analyses performed with riboWaltz, I would suggest to use the _create_annotation_ function to retrieve what you need rather than manually compute it. From the annotation data.table, you can easily get the CDS start and CDS end position using the length of the 5'UTR and the CDS:

- CDS start: length 5'UTR + 1
- CDS end: length 5'UTR + length CDS

But, if you want to run the lines computing the length of UTRs and CDS, here is the code (data.table package required):

```
txdbanno <- GenomicFeatures::makeTxDbFromGFF(file = PATH_TO_GTF, format = "gtf")
exon <- suppressWarnings(GenomicFeatures::exonsBy(txdbanno, by = "tx",use.names=T))
utr5<- suppressWarnings(GenomicFeatures::fiveUTRsByTranscript(txdbanno,use.names=T))
cds <- suppressWarnings(GenomicFeatures::cdsBy(txdbanno, by = "tx", use.names=T))
utr3<- suppressWarnings(GenomicFeatures::threeUTRsByTranscript(txdbanno,use.names=T))
exon <- as.data.table(exon[unique(names(exon))])
utr5 <- as.data.table(utr5[unique(names(utr5))])
cds <- as.data.table(cds[unique(names(cds))])
utr3 <-as.data.table(utr3[unique(names(utr3))])

anno_df <- exon[, list(l_tr = sum(width)), by = list(transcript = group_name)]
l_utr5 <- utr5[, list(l_utr5 = sum(width)), by = list(transcript = group_name)]
l_cds <- cds[, list(l_cds = sum(width)), by = list(transcript = group_name)]
l_utr3 <- utr3[, list(l_utr3 = sum(width)), by = list(transcript = group_name)]

merge_allx <- function(x, y) merge(x, y, all.x=TRUE)
anno_df  <-  Reduce(merge_allx, list(anno_df, l_utr5, l_cds, l_utr3))
anno_df[is.na(anno_df)] <- 0
```

If you still have discrepancies in the results wrt what riboWaltz returns, be sure you are using the very same GTF file.


Hope it helps.

Best
Fabio

**Comment by Xuan0318** [comment]
Hi Fabio,

Thank you for your help! I used your code with gencode gtf and the result is same as the Ensembl Biomart. It is not a good choice to reinvent the wheel since I could not treat some unusual tags like alternative_3_UTR and alternative_5_UTR in gtf. Thank you again for your help and your software.

Best,
Yuxuan

**Comment by fabiolauria** [comment]
Hi Yuxuan,
happy to hear you manage to solve your issues.
Let me know if you need additional help.

Best
Fabio
