### ISSUE TITLE
High RAM usage / efficiency issues

### ISSUE THREAD

**Issue by bontus** [LabTranslationalArchitectomics/riboWaltz#4]
Hi,
Sorry for continuously creating new issues, but I think this is a fundamental one if you want to release a successful package: it's current RAM usage is staggering. The machine I am working features 32GB of RAM and my dataset consists of 8 samples (2 conditions with quadruplicates, human cells, most samples between 15-25mio reads, one sample with 83mio), however, I am not able to run psite_info() without entirely filling up all memory, causing Linux to start swapping. I have managed to mitigate the issue partially by introducing a couple of gc() calls inside your functions (at the end of every iteration of bamtolist, psite and psite_info), however, storing all reads in a list which is effectively duplicated upon running psite_info() absolutely kills my machine. Currently, I am taking apart psite_info() so as to update the existing "reads_list" data frame directly, however, I don't think this is feasible for everyday use unless it is done within the package itself.
Also, one simplistic idea to reduce the overhead could be to deduplicate the "reads_list" data frame by adding a "count" column that stores how often a particular read (= equal mapping information) has been found and to adapt downstream code accordingly.

Best,
René

**Comment by fabiolauria** [comment]
Hi René,
thank you again for your feedback. Actually, all your efforts to test, use and comment the package are welcome so keep going opening new issues when it's needed.
I see your point here. I have never faced the same problem since I have always worked with smaller datasets. Nevertheless, I thought quite a lot about the best option for reducing memory overloading.
Something similar to your last suggestion has been already taken into account for avoiding, at least, reads duplicates belonging to the same sample to be present more than once. Another option would be to "merge", with some additional work, the data frames of the list in a single object avoiding reads duplicates belonging to _many_ samples to be present more than once (even if for the user would be more difficult to go through the data).
I didn't understand your sentence "I am taking apart psite_info() so as to update the existing "reads_list" data frame directly". If it's something that can be easily implemented I could start from there as a first step.
Anyway, I'll think something else for solving this issue. It will take some time since it affects all the downstream functions but I'll work on it. Meanwhile, I can add some gc() in the code, just to soften the issue.

Bests,
Fabio

**Comment by bontus** [comment]
Hi Fabio,
to clarify, I meant that psite_info() duplicates reads_list internally in order to add the psite information for each data frame and then returns the newly created list as reads_psite_list, so basically you take a large object, duplicate it and then make it even larger. What I therefore did was to circumvent calling psite_info() altogether and instead extract the code, add the psite information columns to each data frame containing the reads (df <- reads_list[[n]]) and then storing the new df in reads_list instead of creating a new list (reads_list[[n]] <- df2, hence "updating").
Nonetheless, *spoiler alert*, this was not sufficient to process the "biggest" sample, so I ended up redesigning the workflow to work with one sample only and then looping through my BAM files and calling the script from the command line. Not exactly what I was hoping for, but it still got me what I wanted ;)
I created a fork of your project as I noticed a bug (removed line 62 of psites.R as it breaks the function) and uploaded the mentioned R script for cmd line, so feel free to have a look.

Best,
René

**Comment by fabiolauria** [comment]
Hi René,
ok _now_ I see your point, sorry for the misunderstanding and thanks for your additional explanation.
Running psite_info on each data_frame separately is for sure a good option for reducing RAM usage, further decreased running the entire workflow starting from single BAM files. I can add a warnings in the documentation about this issue, also pointing to your script and patch, if it's ok.
Nevertheless, I'll keep looking for a solution that allow the use of riboWaltz on multiple samples simultaneously without splitting the data, if possible (e.g. by grouping the read duplicates together reducing the size of the data frames, as I mentioned in my last post).

Bests,
Fabio

PS: thank you also for highlighting the bug.

**Comment by bontus** [comment]
Hi Fabio,

Glad I could help and feel free to point to my script or modify it as you please. Just FYI, the provided patch file is actually no longer necessary once the psite() bug has been fixed, as your functions also work with a single sample given that it is provided as a list.
Anyway, I agree that a note in the documentation is a good idea, maybe including some estimates of RAM usage depending on the number of reads? Since the issue is being worked on, I will close this thread for now and let you know if I run into any other problems ;)

Best

**Comment by fabiolauria** [comment]
Hi Renè,
I'm reopening this issue just to inform you that I loaded a temporary function called psite_info_dt that works as psite_info but handling data tables instead of data frames. This trick speed the update of the datasets up and everything is more efficient also from the point of view of the RAM usage.
I already tested it on my laptop (16 Gb RAM) with a list of 8 "fake" samples of size similar to what you described in your first comment (7 with 18mio reads and 1 with 75mio reads). In less than 30 sec the whole process ended without any error concerning allocation or memory usage.
However, I'm wondering if you would like to try with your own data, also to be sure it actually works with real samples. If so, remember to convert both the element in reads_list and the data frame with the offsets in data tables before running psite_info_dt:

```
library(data.table)

offsets <- data.table(offsets)
for(n in names(reads_info)){
reads_info[[n]] <- data.table(reads_info[[n]])
}

reads_info <- psite_info_dt(reads_info, offsets) 
```

Just to be clear, up to know I implemented the new function modifying the "core" of psite_info i.e. the generation of additional columns reporting all the P-site information but the nucleotide sequences covered by the P-sites (optional).
If it works fine, it would be a good idea to extend the use of data tables to all the most RAM- and time-consuming functions.

Bests
Fabio
