### ISSUE TITLE
Error Codon Coverage

### ISSUE THREAD

**Issue by FranziMe** [LabTranslationalArchitectomics/riboWaltz#43]
Hi, 

Thanks for your great tool. we have been using it a bit.
I am trying to get the number of P-sites per Codon (or actually A-sites, but I will just shift the numbers by one codon).

I am trying to use the function `codon_coverage()` for that.

The function works perfectly fine with `psite=FALSE`:
```
codon_coverage_list <- codon_coverage(reads_psite_list, ANN, psite = FALSE)
1. creating codon table and computing distance from start/stop codon
2. acquiring region information
3. computing codon coverage based on read footprints
sample : RiboSeq_glp1_luci_1
sample : RiboSeq_glp1_luci_2
....
```

However if I try to get the p-sites per Codon using `p-site=TRUE` I get the following error:
```
1. creating codon table and computing distance from start/stop codon
2. acquiring region information
3. computing codon coverage based on P-sites
sample : RiboSeq_glp1_luci_1
Error in .Call2("C_solve_user_SEW0", start, end, width, PACKAGE = "IRanges") : 
  In range 3: at least two out of 'start', 'end', and 'width', must
  be supplied.
```

I have tried returning a granges object from length_filter:
```
filtered_list <- length_filter(data = reads_list, length_filter_mode = "custom",
                                          length_range = 28:33, granges = TRUE)
```

but that lead to crashing of the `psite()` function
```
psite_offset = psite(filtered_list, plot = TRUE, plot_dir = "~/ribowaltz_out/", plot_format = 'pdf')
processing RiboSeq_glp1_luci_1
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'j' in selecting a method for function '[': Check that is.data.table(DT) == TRUE. Otherwise, := and `:=`(...) are defined for use in j, once only and in particular ways. See help(":=").
```

sessionInfo()
```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.2 LTS

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.8.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=C              LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] data.table_1.14.0 riboWaltz_1.2.0   wesanderson_0.3.6 pheatmap_1.0.12   openxlsx_4.2.3    rstatix_0.7.0     forcats_0.5.1     ggpubr_0.4.0     
 [9] ggplot2_3.3.3     readr_1.4.0       dplyr_1.0.6       tidyr_1.1.3      

loaded via a namespace (and not attached):
 [1] matrixStats_0.58.0          bitops_1.0-7                bit64_4.0.5                 RColorBrewer_1.1-2          progress_1.2.2             
 [6] httr_1.4.2                  GenomeInfoDb_1.26.7         tools_4.0.4                 backports_1.2.1             utf8_1.2.1                 
[11] R6_2.5.0                    DBI_1.1.1                   BiocGenerics_0.36.1         colorspace_2.0-1            withr_2.4.2                
[16] tidyselect_1.1.1            prettyunits_1.1.1           bit_4.0.4                   curl_4.3.1                  compiler_4.0.4             
[21] cli_2.5.0                   Biobase_2.50.0              xml2_1.3.2                  DelayedArray_0.16.3         labeling_0.4.2             
[26] rtracklayer_1.50.0          scales_1.1.1                askpass_1.1                 rappdirs_0.3.3              digest_0.6.27              
[31] stringr_1.4.0               Rsamtools_2.6.0             foreign_0.8-81              rio_0.5.26                  XVector_0.30.0             
[36] pkgconfig_2.0.3             MatrixGenerics_1.2.1        dbplyr_2.1.1                fastmap_1.1.0               rlang_0.4.11               
[41] readxl_1.3.1                rstudioapi_0.13             RSQLite_2.2.7               farver_2.1.0                generics_0.1.0             
[46] BiocParallel_1.24.1         zip_2.1.1                   car_3.0-10                  RCurl_1.98-1.3              magrittr_2.0.1             
[51] GenomeInfoDbData_1.2.4      Matrix_1.3-2                Rcpp_1.0.6                  munsell_0.5.0               S4Vectors_0.28.1           
[56] fansi_0.5.0                 abind_1.4-5                 lifecycle_1.0.0             stringi_1.6.2               carData_3.0-4              
[61] SummarizedExperiment_1.20.0 zlibbioc_1.36.0             BiocFileCache_1.14.0        grid_4.0.4                  blob_1.2.1                 
[66] ggrepel_0.9.1               parallel_4.0.4              crayon_1.4.1                lattice_0.20-41             Biostrings_2.58.0          
[71] haven_2.4.1                 GenomicFeatures_1.42.3      hms_1.1.0                   pillar_1.6.1                GenomicRanges_1.42.0       
[76] ggsignif_0.6.1              biomaRt_2.46.3              stats4_4.0.4                XML_3.99-0.6                glue_1.4.2                 
[81] vctrs_0.3.8                 cellranger_1.1.0            gtable_0.3.0                openssl_1.4.4               purrr_0.3.4                
[86] assertthat_0.2.1            cachem_1.0.5                broom_0.7.6                 tibble_3.1.2                GenomicAlignments_1.26.0   
[91] AnnotationDbi_1.52.0        memoise_2.0.0               IRanges_2.24.1              ellipsis_0.3.2             
```

Any help or suggestions are gratefully appreciated!

Best Wishes,
Franzi

**Comment by fabiolauria** [comment]
Hi Franzi,
I had the chance to take a look into your issues.

Sorry, at first I missed the one related to the granges object and the _psite()_ function, that is easily adressed: none of riboWaltz's functions support granges object as input data. It's true that you can return such objects from multiple functions, as explicitly requested by some users. However, this option aimed at easing downstreaming analysis on ranges defined by read footprint projections. I don't know why, but I never thought of allowing grange objects as inputs. I will add this feature in the next versions.

Regarding the _codon_coverage()_ issue, the function smoothly worked on a dataset of mine, on which I run the following command (where psite_list_dedup is a list of 3 data tables and `psite` is set to TRUE):

`test_codon_cov <- codon_coverage(psite_list_dedup, annotation = anno17, psite = "TRUE")`

Given this, the chunk of code within _codon_coverage()_ dealing with your input data.table and that takes into account `psite` is more or less the following one (I'm using the name of your structure and only one sample):

```
dt <- reads_psite_list[[1]]

if(psite == T || psite == TRUE){
 gr_read <- GenomicRanges::GRanges(seqnames = dt$transcript,
                                        IRanges::IRanges(dt$psite, dt$psite),
                                        strand="+")
} else {
 gr_read <- GenomicRanges::GRanges(seqnames = dt$transcript,
                                        IRanges::IRanges(dt$end5, dt$end3),
                                        strand="+")
}
```

After this, the function performs the overlap between gr_read and the granges structure containing the range of all triplets for each transcripts, independently of the `psite` parameter. So I guess it's here that your issue arises, maybe because _codon_coverage()_ cannot find the psite column in dt for one or multiple samples? Or because in that column some psites are set to NA?


I hope this might help. Let me know.

Best
Fabio

**Comment by FranziMe** [comment]
Hi Fabio,

Thank you so much for checking. I feel quite stupid now.
I did have some NA's in the `psite` column of each sample. 
I removed these lines and the function ran perfectly fine now.

Thanks again!
Franzi

if anybody encounters the same problem:
```# remove rows where psite == NA
reads_psite_list_clean = list()
for(i in names(reads_psite_list)){
  tmp = reads_psite_list[[i]]
  tmp = subset(tmp, !is.na(psite))
  reads_psite_list_clean[[i]] = tmp
}
```

**Comment by fabiolauria** [comment]
Hi Franzi,
I'm glad to hear everything is fine now.

However, I think something went wrong with the _psite()_ function in the first place. Otherwise you wouldn't have had NA's in the psite column after running _psite_info_. Initially, only the read lengths not used for inferring the corrected offset itself (i.e. those not mapping on the start - or stop - codon) are associated to NAs p-site offsets by _psite()_. However, the corrected offset is then associated by default to all of them. To this aim, the code uses one of the following lines, according to the best extremity:

`psite_offset[is.na(corrected_offset_from_3), corrected_offset_from_3 := best_offset]`

or

`psite_offset[is.na(corrected_offset_from_5), corrected_offset_from_5 := best_offset]`

where **psite_offset** is the data table reporting the inferred p-site offsets. The corrected_offset_from_3 or the corrected_offset_from_5 are then exploited to compute the p-site position for each data table in **filtered_list** according to the corresponding read lengths. So, in principle, no NA's should be present.

May I bother you by asking for those lines of your **psite_offset** data table associated to NAs either in the column corrected_offset_from_5 or corrected_offset_from_3? I'm curious to know if we are talking about underrepresented population of reads or not. 

Obviously, everything I wrote make sense if you followed riboWaltz's pipeline without handling or modifying the original data tables.

Please let me know, so I would know if and how modify the functions.

Best
Fabio

**Comment by FranziMe** [comment]
Hi Fabio,

sure. This is my workflow from BAM files to where I calculate the p-site coverage
```

library(riboWaltz)
library(ggplot2)
library(openxlsx)
library(data.table)

# reformat Annotation
print("create annotation")
ANN = create_annotation(gtfpath = 'caenorhabditis_elegans/103/original.gtf')

# convert star bam file to bed
print("convert star bam to bed")
bamtobed(bamfolder = "ribowaltz_out/", bedfolder = "ribowaltz_out/")

# read in sample files
print("load sample files")
reads_list <- bedtolist(bedfolder = "ribowaltz_out/", annotation = ANN)

# rename samples
sample_sheet=read.csv('20210722RiboSeq.csv')
row.names(sample_sheet) = paste0(sample_sheet[,'Sequencing'], '_', sample_sheet[,'SampleName'])
names(reads_list) = gsub('.Aligned.toTranscriptome.out', '', names(reads_list))
sample_sheet.ribo = subset(sample_sheet, Sequencing == 'RiboSeq') # there are also RNAseq samples, but I am excluding those from the Ribowaltz analysis

# reorder list according to sample sheet
reads_list = reads_list[row.names(sample_sheet.ribo)]

# Filter by readlength
print('filter reads by read length')
filtered_list <- length_filter(data = reads_list, length_filter_mode = "custom",
                               length_range = 28:33)

# get p-site offset
print('calculate p-site offset')
psite_offset = psite(filtered_list, plot = FALSE)

reads_psite_list <- psite_info(reads_list, psite_offset)

# get cds coverage
print('get cds and codon coverage')
cds_coverage_list <- cds_coverage(reads_psite_list, ANN) 

# get codon coverage
codon_coverage_list <- codon_coverage(reads_psite_list, ANN, psite = FALSE)


# remove rows where psite == NA
reads_psite_list_clean = list()
for(i in names(reads_psite_list)){
  tmp = reads_psite_list[[i]]
  tmp = subset(tmp, !is.na(psite))
  reads_psite_list_clean[[i]] = tmp
}
codon_coverage_list_psite <- codon_coverage(reads_psite_list_clean, ANN, psite = TRUE)


```
this is the first six lines of an example of the reads_psite_list:
```
> head(reads_psite_list$RiboSeq_glp1_luci_1)
   transcript end5 psite end3 length cds_start cds_stop psite_from_start psite_from_stop psite_region
1:  2L52.1a.1   69    81   97     29        20     1303               61           -1222          cds
2:  2L52.1a.1   69    81   97     29        20     1303               61           -1222          cds
3:  2L52.1a.1  317    NA  340     24        20     1303               NA              NA         5utr
4:  2L52.1a.1  402    NA  428     27        20     1303               NA              NA         5utr
5:  2L52.1a.1  457    NA  482     26        20     1303               NA              NA         5utr
6:  2L52.1a.1  457    NA  482     26        20     1303               NA              NA         5utr
```
Is this enough or do you need more.

After a second look it seems like the NA's are for reads with the length that I had previously discarded. Maybe I mis-understood the tutorial.
Do I need to run the `psite` function on the full reads list or the filtered reads list?

attached is an overview of my read-length distribution
[raw_read_length(1).pdf](https://github.com/LabTranslationalArchitectomics/riboWaltz/files/7486448/raw_read_length.1.pdf)

**Comment by fabiolauria** [comment]
Thank you so much Franzi.

So you 1) filtered your data tables discarding specific read lengths (fine) and 2) computed the psite offsets on the remaining read lengths (fine). At this point, riboWaltz can infer the p-site position **only for those read lengths which have been previously associated to a specific offset** by _psite()_. This means that if you select reads of length 28-33 nts and use the filtered list to run _psite()_, p-site offsets will be available only for reads of length 28-33 nts. You can verify this by looking at your _psite_offset_ data table, where information about the p-site offset should be present only for reads of length 28-33 nts.
Given this, when you tried to infer the p-site localization by _psite_info()_ for **all** the reads, riboWaltz didn't know what to assign to the read lengths not in the range 28-33 nts. So, instead of 

`reads_psite_list <- psite_info(reads_list, psite_offset)`

you should have run 

`reads_psite_list <- psite_info(filtered_list, psite_offset)`

and the same is true for all downstream analyses.
Otherwise, the filtering step would have been pointless if not detrimental, because your are still using all reads, but their p-site is computed by excluding a portion of them.

Sorry if it wasn't clear in the readMe. I'll change it.


If everything is clear, feel free to close the issue.

Best
Fabio

**Comment by FranziMe** [comment]
Ah That makes perfect sense now. 
Yes, I copied most of the commands from the tutorial but must have not been aware of the specific read_list

Thank you again for your help!

Best wishes,
Franzi
