### ISSUE TITLE
reads_list No results generated，No errors reported

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#47]
when i use the command：
"annotation_dt<-create_annotation(gtfpath='E:/riboseq/NSP306_trifida_chr_v3.gtf')"
"reads_list <- bamtolist(bamfolder = "E:/riboseq/totalreadsAligned.sortedtoTranscriptome.out.bam", annotation = annotation_dt)"
No results generated，No errors reported，
then i try command
“reads_list <- bamtolist(bamfolder = "E:/riboseq/totalreadsAligned.sortedtoTranscriptome.out.bam", annotation = 'E:/riboseq/NSP306_trifida_chr_v3.gtf')”
No results generated，No errors reported
that is why？
thanks！

**Comment by fabiolauria** [comment]
Hi there.
I see at least one problem in this line

`reads_list <- bamtolist(bamfolder = "E:/riboseq/totalreadsAligned.sortedtoTranscriptome.out.bam", annotation = annotation_dt)`

 `bamfolder `should be a **folder**, not a single BAM file. As reported in the documentation: 

> bamfolder: character string specifying the path to the folder storing BAM files

In your second attempt

`reads_list <- bamtolist(bamfolder = "E:/riboseq/totalreadsAligned.sortedtoTranscriptome.out.bam", annotation = 'E:/riboseq/NSP306_trifida_chr_v3.gtf')`

also the `annotation` parameter is wrong. Because, as you correctly did the first time, it should correspond to the data table generated by _create_annotation_.

Let me know what happens by changing `bamfolder`. If everything is fine, feel free to close the issue. And please remember to always read carefully the ReadMe and the documentation.

Best,
Fabio

**Comment by z626093820** [comment]
thanks，the problem is solved using your advice
