### ISSUE TITLE
Inquiry about the article "riboWaltz: Optimization of ribosome P-site positioning in ribosome profiling data“

### ISSUE THREAD

**Issue by z626093820** [LabTranslationalArchitectomics/riboWaltz#55]
There is an ORF that can be translated into a short peptide in the 5'UTR region, so there should be a periodicity of high low low, and the TIS accuracy score is judged by the period to determine whether it must be correct? Thank you!
![image](https://user-images.githubusercontent.com/37371455/154480369-cbe4d15e-28ed-47b8-b5e3-26d92024e7f6.png)

**Comment by z626093820** [comment]
Thank you very much for your answer! I have another question, is it possible to analyze reads -through from Ribo-seq and extract transcripts with reads in the 3'UTR region?

**Comment by fabiolauria** [comment]
I think it's possible to obtain some clues about potential readthroughs. The only way I can think of is: 1) compute the P-site offset and add the P-site position for each read so to also have their localization in terms of transcript region (i.e. if they fall in the 5'UTR, the CDS or the 3'UTR); 2) add info about the P-site frame on the CDS and on the UTRs; 3a) check for all transcripts the periodicity - if any -  in the first part of the 3'UTR and select only those transcripts showing more P-sites in frame 0 than in frame 1 or 2 (as expected for translating ribosomes); 4) perform a manual meteprofile around the stop codon using the selected transcripts.
It's not straightforward and there are some steps to be performed manually, but it should work. If you are not interested in looking for periodicity and translating ribosomes on the 3'UTR but only in finding ribosomes "sliding" or stalled on the 3'UTR, it's more simple because it's just a matter of how much the beginning of the 3'UTR is covered by RiboSeq reads wrt the CDS or the whole transcript.
