### ISSUE TITLE
psite error

### ISSUE THREAD

**Issue by janhavikolhe** [LabTranslationalArchitectomics/riboWaltz#59]
Hi!

I generated the annotation table and data list. When I ran the rlength_distribution, the plot looked fine
![W0-Library1](https://user-images.githubusercontent.com/69176496/180661957-10ca7a1f-d17f-42d4-b9d1-015e374d9242.png)

However, my annotation dataset does look weird (attached file) - the 5' and 3' utrs are not annotated for some reason even though i used txdb to generate the annotation. As a result, my bamtolist result also doesn't have the utr information.

When I run psite on my data I get the following errors

Error in if (extremity == "auto" & ((best_from3_tab[, perc] > best_from5_tab[,  : 
  argument is of length zero
In addition: Warning messages:
1: In min(site_sub$length) :
  no non-missing arguments to min; returning Inf
2: In max(site_sub$length) :
  no non-missing arguments to max; returning -Inf
3: In max(perc) : no non-missing arguments to max; returning -Inf
4: In max(perc) : no non-missing arguments to max; returning -Inf

Thank you so much for your help
[annotation_dt.txt](https://github.com/LabTranslationalArchitectomics/riboWaltz/files/9176487/annotation_dt.txt)
!

**Comment by fabiolauria** [comment]
Hi there.
I had a look at your annotation_dt and I noticed your are working with yeast. The main problem of this organism is that the UTRs are often not annotated. Thus, even if a txdb object is used to run _create_annotation_, the function is not able to include the length of the UTRs in the resulting table.
Please check [this issue](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/42) out for further details and some suggestions for dealing with yeast transcripts.

Let me know how it goes.

Fabio

**Comment by janhavikolhe** [comment]
Hi Fabio,

I read the entire thread and unfortunately, I don't think that solution will work for me. I am specifically interested in initiation from non-canonical sites and was hoping to use the psite function of ribowaltz and the frame plots to show that my mutant strain had reduced number of psites in the 0 frame. I assume this would require proper 5' and 3' UTRs?

I am not very adept at bioinformatics and this is my first time trying to do this kind of analysis, so I am not sure I could create an appropriate fasta or gtf file myself.

Would you happen to have a workaround for this?

Thank you!

Sincerely,

Janhavi

**Comment by fabiolauria** [comment]
Hi Janhavi.
Unfortunately I have no workaround for this. As you read in the previous thread about yeast sequences issues, I didn't really go into details about how to extract the required information and generate proper file. I'm pretty sure it takes some time, but that's all I can say. You can try to contact the user from the other issue and talk with him.
Anyway, I don't think you need "proper" (= real) 5' and 3' UTRs for this. But since you want to look at initiation sites upstream the canonical ones, you will have to carefully choose the flanking regions to be manually added to the CDS in the FASTA e annotation files. So you can be be sure the sequence stretches of interest are included.
The only problem I can see here is: if the the mutant strain leads to non-canonical starting sites for only a subset of mRNAs (i.e. if this there are no transcript-wide effects), this information will be lost in the mess of RNAs that are not affected by the mutations. Thus, be sure to take into account the "correct" population of mRNAs when inspecting the frames.

Given this, since this issue is not strictly related to an error of riboWaltz but rather an annotation issue, I will keep this issue open for a couple of weeks and then, if there are no updates, I will close it. in the meantime feel free to post additional questions and/or anything you think it might be of some help for other users.

Best
Fabio

**Comment by janhavikolhe** [comment]
Hi Fabio,

I did get the UTR lengths from Pelenchalo et al 2013 for about 5200 genes out of 6692. However, while I was doing the analysis I realised that I had aligned my reads to the orf_coding_all.fasta from SGD which doesn't have the 5'-UTR or 3'-UTR sequence included. Would this make a difference to how RiboWaltz assesses the psite offset? The annotation file has the information but since the reference for the alignments did not, would I have to realign everything to a more appropriate fasta file?

Thank you!

Sincerely,

Janhavi

(Description - ORF Coding Sequences (CDS) only, without 5'-UTR, 3'-UTR, intron sequences, or bases not translated due to translational frameshifting.  For all ORFs.)

**Comment by fabiolauria** [comment]
Hi Janhavi.
Aligning your reads to a FASTA file which does not match the information included in the annotation file is not the right procedure for applying **riboWaltz** afterwards. In your case:

1. there would obvious differences between the length of the FASTA sequences and the length of the transcripts in the annotation file. This aspects alone would cause errors here and there, so you must be sure both FASTA and annotation file are based on the same sequences.
2. the major issue is the absence of stretches of nucleotides flanking the CDS in the FASTA file. This means that no read can be mapped on the reference codon (either the start codon or the second to last codon). These reads that are used to compute the P-site offset, so **riboWaltz** will throw errors at almost every step.

Concluding, the answer is yes: you should realign everything to a more appropriate FASTA file that includes UTRs of the same length as reported by the annotation file. There will be a bit of manual work to do I guess.

Best
Fabio

**Comment by janhavikolhe** [comment]
Hi Fabio,

Thank you so much. Surprisingly, I haven't gotten any errors at all. As long as I provide the annotation file with numbers for the UTRs and an alignment I am able to generate the frameshift_psite plots at the very least and the data looks normal - most reads in frame 0.

Regardless, I will try to figure out how to get the fasta file with the UTRs for each cds so that I can realign everything.

Thank you.

Sincerely,

Janhavi

**Comment by fabiolauria** [comment]
Hi Janhavi.
I'm happy to hear you got the plot you where looking for. As you said and according to my previous comments, it is quite astonishing **riboWaltz** succeeded, but as long as it works, it's fine with me :)

Since the issue seems to be solved, I'll close it.
If you need more help, do not hesitate to contact me again.

Best
Fabio
