### ISSUE TITLE
some questions about Codon usage

### ISSUE THREAD

**Issue by ELMMA-FUNNY** [LabTranslationalArchitectomics/riboWaltz#67]
Hello!
   When I used codon_usage_psite()
WT1_cu_barplot <- codon_usage_psite(reads_psite_list, annotation_dt, sample = "WT1",
                                        fastapath = "/home/lulu/chenhui_project/reference/GRCm38.size/GRCm39.genome.fa",
                                      refseq_sep = " ",
                                      fasta_genome = FALSE,
                                      frequency_normalization = FALSE) 
The erreor was:
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names

Before using it ,I  chose one peremeter refseq_sep = " " , for my FASTA file reports for the first chromosome,"chr 1"and my GTF file reports "chr1".
But it still runs with error.I don't konw how to solve it.
Could you help me?
THANKS. 
ELMMA-FUNNY

**Comment by fabiolauria** [comment]
Hi there,
thank you for using **riboWaltz**.
I have some comments based on your code 
```
WT1_cu_barplot <- codon_usage_psite(reads_psite_list, annotation_dt, sample = "WT1",
fastapath = "/home/lulu/chenhui_project/reference/GRCm38.size/GRCm39.genome.fa",
refseq_sep = " ",
fasta_genome = FALSE,
frequency_normalization = FALSE)
```
and your description of the FASTA and GTF file.

1. your FASTA file contains chromosome sequences so _fasta_genome_ should be set to TRUE and _gtfpath_ is required.
2. mismatching chromosome names in the FASTA and the GTF ("chr 1" vs "chr1") suggests the two files come from different sources/databases/repositories, otherwise the use of _refseq_sep_ should be sufficient to make sequences names matching.

Please check [issue 39](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/39) and let me know if you manage to get rid of the error. Otherwise, we will take a deeper look into your data and files.

Best
Fabio

**Comment by ELMMA-FUNNY** [comment]
Thank you for your suggestion.It works good.
But I got another question.The rate of AUG(the start coden) usage is not the most.
How was that?Is there any problem with my data or analysis code?
Thanks,
ELMMA-FUNNY

**Comment by fabiolauria** [comment]
Hi,
happy to hear everything is fine now.
Regarding the usage of AUG wrt other codons, given that _frequency_normalization_ in your example is set to FALSE, you are right and your results are a bit odd. I can only think of duplicated reads that possibly pile up on specific positions. Did you removed them?

Best
Fabio

**Comment by ELMMA-FUNNY** [comment]
Hi,
I didn't remove the duplicated reads.

**Comment by fabiolauria** [comment]
Okay then it's possible some positions (thus codons) are covered by lots of duplicated reads. These reads might be either biologically relevant i.e. deriving from ribosome pausing or PCR duplicates. There is not really a way two tell them apart, but the consequence is the same: skyscrapers of reads on specific triplets (most likely the ones that from your analysis result to be more covered).
You can dig a bit into your data looking for the most recurrent pair of 5' end and 3' end within the same transcript to find out if this is the case.

Best
Fabio

**Comment by fabiolauria** [comment]
Hi there,
did you figure out what was going on with your data? Does everything work now?

Let me know how it goes.

Best
Fabio
