### ISSUE TITLE
Quantification of overall p-site & a-site occupancy for each transcript

### ISSUE THREAD

**Issue by bontus** [LabTranslationalArchitectomics/riboWaltz#7]
Hi Fabio,

I was wondering if you could implement a function to count the total number of reads covering each of the 64 codons for each transcript based on the p-site as well as the **a-site**. This would be very useful for calculating whether ribosome footprints are observed more often than expected for one codon (= possible ribosome stalling due to low tRNA concentration).
Conceptually you should be able to re-use most of the code from codon_usage_psite(), this is what I did previously.
BTW, the new version works quite well, I have yet to test it with the problematic sample, but it seems that I can run another dataset in its entirety without swapping (clearly using > 16 GB RAM though).

Best,
René

**Comment by fabiolauria** [comment]
Hi René,
following yuor suggestion I updated the codon_usage_psite function introducing the parameter "site". It allows to chose one of the three ribosome sites for computing the "empirical codon usage indexes" i.e. the normalized number of reads covering each of the 64 codons. On the same line I modified the psite_info function introducing the possibility to add one ore more columns reporting the nucleotide sequence covered not only by the P-site but also by the A-site or the E-site (again through the "site" parameter).

Bests,
Fabio

**Comment by bontus** [comment]
Hi Fabio,

Thanks for the quick implementation, seems to work fine. Could you elaborate on the normalization you use?

Best

**Comment by bontus** [comment]
Hi Fabio,
Thanks for the clarification! I think it would be great to make these normalization steps optional, as I think you are falsely estimating the background frequency of your codons by not taking into account gene expression. For instance, if a CDS consists of 10000 AAA but its mRNA is not expressed, it will nonetheless increase the "background" codon frequency by 10000 AAA and 0 for all other codons in your correction table.
To fix this, it would be necessary to return the counts of all 64 codons for each mRNA supplied to the function so that they can be normalized by mRNA expression subsequently.

Best

**Comment by fabiolauria** [comment]
Hi René.
I have thought quite a bit about your concerns on the normalization step, coming to the following conclusion: possibly, an issue can be found in the foreground rather than in the background (a subtle but significant difference to me). In fact, I think it is correct to employ codon frequencies based also on those triplets showing a low or no coverage (by the way, I would suggest to apply some filters at the beginning of the analysis to discard mRNAs with no coverage at all). For _transcript-specific codon usage bias index_ the codon coverage must be normalized for the codon frequencies along the mRNA, too. Nevertheless, as you pointed out, an additional normalization step based on the mean coverage of the mRNA should be introduced to properly weight the foreground.
I will introduce such a normalization coupled with a parameter to opt for using the average mRNA-specific Ribo-Seq coverage or to supply external scale factors (e.g. based on RNA-Seq data). Regarding the plots, at least for single-sample analysis I would opt for representing the result through 64 boxblots rather than a barplot.
I'll leave this issue open until I get everything done. It might take a while since I'm quite busy.

Bests,
Fabio

**Comment by bontus** [comment]
Hi Fabio,
Perhaps we are talking in different terms, with background I meant the all codons of the transcriptome, which as I explained should be limited to only the "active" transcriptome in my opinion. Regardless, I am curious about your normalization but at the same time still think it is worthwhile to include an option to return the raw footprint distribution per transcript. To solve the issue for now, I simply added two small chunks of code, see below, I only include the P-site example here.
Where you calculate norm_table,
`if (site == "psite") {norm_table <- data.table(table(factor(dt$p_site_codon, levels = cod_lev)))}`
I simply introduced this extra line:
`raw_table <- matrix(unlist(tapply(factor(dt$p_site_codon,levels=sort(gsub('U','T',cod_aa$codon)))`
and added it to the return:
`output[["raw_rpf"]] <- raw_table`

Best

**Comment by fabiolauria** [comment]
Hi Renè,
I added the parameter _frequency_normalization_ in function _codon_usage_psite_ allowing the user to choose whether normalize the codon usage indexes for codons frequencies in sequences. I thought better of my idea of a transcript-specific normalization, since I preferred do maintain the results as smooth as possible and easy to interpret so far.

Bests
Fabio
