### ISSUE TITLE
Questions about codon_usage_psite

### ISSUE THREAD

**Issue by DaehoJoe** [LabTranslationalArchitectomics/riboWaltz#72]
Hello
I am currently trying to generate a graph using command "codon_usage_psite" with following commands.

I have aligned my sequences using STAR (v 2.7.10b) with its option -quantMode TranscriptomeSAM through gencode GRCh38v43 reference. 

I generated annotation_table using the same annotation file used while alignments, with following commands.
```
annotation_table <- create_annotation(gtfpath = "~/Documents/reference/gencode.v43.chr_patch_hapl_scaff.annotation.gtf")
```
I've got some warning messages.
```
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names
```

Following those steps above, when I run the commands below, I get errors..
```
cu_barplot <- codon_usage_psite(reads_psite_list,
                                annotation_table,
                                sample = "RPF2",
                                fastapath = "~/Documents/reference/gencode.v43.transcripts.fa",
                                fasta_genome = FALSE,
                                frequency_normalization = FALSE)
```
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'subseq': subscript contains invalid names
```

I have already checked [issue 39](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/39) and [issue 67](https://github.com/LabTranslationalArchitectomics/riboWaltz/issues/67),  but cannot find a way to solve my problem.

I am using riboWalts v1.2.0 and R version 4.2.3 in platform aarch64-apple (M1 mac).

Could you please help me??

Thank you.

Daeho

**Comment by DaehoJoe** [comment]
Thank you for your kind answer.

Following your suggestion, I have changed "fasta_genome = TRUE" and also added gtfpath.

Still, same error message is showing up..

Here is modified commands.
```
cu_barplot <- codon_usage_psite(reads_psite_list,
                                annotation_table,
                                sample = "RPF2",
                                fastapath = "~/Documents/reference/GRCh38.p14.genome.fa",
                                fasta_genome = TRUE,
                                gtfpath = "~/Documents/reference/gencode.v43.chr_patch_hapl_scaff.annotation.gtf",
                                frequency_normalization = FALSE)
```
 For STAR commands, I used those fasta and gtf files for generating index (--runMode genomeGenerate) and mapped reads with following commands.

```
	STAR --genomeDir /mnt/NAS/reference/STAR_gencode_hg38_v43 \
	     --runThreadN 16 \
	     --readFilesCommand zcat \
	     --readFilesIn $PWD/${i}.fastq.gz  \
	     --outFileNamePrefix /mnt/NAS/primary_output/${i} \
	     --twopassMode Basic \
	     --outSAMtype BAM SortedByCoordinate \
	     --quantMode TranscriptomeSAM
```
Thanks,
Daeho

**Comment by fabiolauria** [comment]
Hi Daeho.
from what I see there is at least one potential issue in your code. The best way to minimize errors popping up because of discrepancies across GTF and FASTA is to get them from the same version of the annotation. Here, you are using _gencode.v43.chr_patch_hapl_scaff.annotation.gtf_ from GENCODE human release **43** and _GRCh38.p14.genome.fa_ from GENCODE human release **44**. This might cause your error.

If that is not the case, to understand what is going on I would need to look to a couple of sequence names from the FASTA file as well as the first rows of the GTF, of one element of reads_psite_list and of annotation_dt (as in Issue #69). BTW, keep in mind the _refseq_sep_ parameter I mentioned above, which is quite often the culprit for many similar issues.

Best
Fabio

**Comment by DaehoJoe** [comment]
Sorry for the late reply.
I am currently going thorough reference files saved in the workstation of our lab. So far, I am pretty sure that I have used gencode v43 for alignment, but not sure why gencode v44 file was included in the folder.. I will re-try with gencode v43 reference directly from the source and post the result soon.

**Comment by fabiolauria** [comment]
Hi Daeho,
the problem might be that for some reason you didn't take into account the parameter _refseq_sep_. As I wrote in my previous message, sometimes there are `potential issues related to characters which should be removed through the _refseq_sep_ parameter` and `the _refseq_sep_ parameter is quite often the culprit for many similar issues.` According to your files,  chromosomes are named "chr1 1", "chr2 2" etc. in your FASTA file and "chr1", "chr2" etc. in your GTF. So to discard everything which is redundant in the FASTA file (after the blank space), you should split the string by setting _refseq_sep = " "_ and then keep the first element (this is what refseq_sep is meant for).

In any case, it's not clear to me if you have re-aligned everything with the matching GTF and FASTA file based on the very same  annotation or if you just changed the files in _codon_usage_psite_. If the latter is the case, **I still expect issues because of different files used for the alignment step and in riboWaltz** (and, in general, it's not a good practice to use non-matching annotation when mapping the reads).

Best
Fabio

**Comment by DaehoJoe** [comment]
Hello Fabio,
I think refseq_sep parameter was the key to resolve my problem.
Sorry for the late reply, and thanks for your kind explaination!!

Thank you again!
Daeho

**Comment by DaehoJoe** [comment]
Hello Fabio,
Sorry for the late reply.
I was kind of lost with managing references, but finally solved the problem.
"split the string by setting refseq_sep = " " " was the key to resolve my problem.

Thank you again for your kind solutions!

Best
Daeho
