### ISSUE TITLE
Bug in region_psite()

### ISSUE THREAD

**Issue by bontus** [LabTranslationalArchitectomics/riboWaltz#8]
Hi Fabio,
I wanted to plot the p-site distribution across different mRNA regions and found that the current version of region_psite() bugs out with the following error:

Error in as.character(transcript) %in% c_transcript : 
  object 'transcript' not found``

Best

**Comment by fabiolauria** [comment]
Hi René.
I just run some tests using the datasets provided in the package and other datasets and I got no errors.
The problem here seems to be related to the column names of the data.table passed either through _data_ or through _annotation_. I guess _data_ is the one to check out since _annotation_ is used at the beginning of the function and also in that case the column "transcript" is involved. Do your data come from the **psite_info** function? If so, could you please check the name of the first column of each data.table of the list?

**Comment by bontus** [comment]
Never mind, I found the issue after some testing. The problem was that the naming of _data_ did not match the provided _sample_, the function works as intended.

Thanks for the super quick response though!
