### ISSUE TITLE
Metaprofile plot peak is higher at the stop codon 

### ISSUE THREAD

**Issue by aswathyseb** [LabTranslationalArchitectomics/riboWaltz#83]
Hi,

Attached is my meta profile plot. I was wondering why the 3'end peak is much larger than the one at the start codon.

<img width="1555" alt="metaplot" src="https://github.com/user-attachments/assets/4035a8e9-b53d-4144-bb97-d2ad88e8f2b3">

This is my first time working with ribo-seq, so I wanted to make sure I am doing everything right.

I am working with yeast genome. Since the UTRs are not annotated, following #42, I created a fasta file with 30 bp upstream and downstream of CDS and mapped the reads to it. Also, I modified the GTF file to include the 30bp coordinates for

 the 5' and 3' UTRs.

The command I used to create the plot is
`
profile_all = metaprofile_psite(psite_list, ann,
                            sample = samples,
                            multisamples = "average",
                            utr5l = 30, cdsl = 150, utr3l = 30,
                            colour = c("red","darkgreen"),
                            plot_style = "facet")`

I look forward to any suggestions/comments.
Thank you

**Comment by fabiolauria** [comment]
Hi there,
thank you for using riboWaltz.
The peak at the end of the CDS in not something new. In some papers, I have seen a peak in that position higher than the rest of the CDS and, sometimes, comparable to the one at the beginning.  It's true that here it's even higher than the first one, but it can depend on the organism, the cell type, the treatment etc. 

One general comment not strictly related to the issue. The metaprofiles look a bit noisy (there clearly is signal out of frame). I would suggest to check and remove some read lengths that may be responsible for this.

Since the peaks you asked about are fine and not related to the tool and the procedure you followed to generate the metaprofiles Is correct, I'm going to close this issue. Feel free to open a new one for additional help.

Best
Fabio

**Comment by aswathyseb** [comment]
Thank you very much for the prompt reply and I really appreciate that your observations.
I will follow your suggestions. Thank you!
